#!/bin/bash

CHANGE_KEYMAP=false

mkdir -p /usr/local/src #create our working directory if it not exist

## FLAG the option ##
while getopts ":a" opt; do
  case $opt in
    k)
      echo "change keymap activated" >&2
      CHANGE_KEYMAP=true
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      ;;
  esac
done

## APT-GET ##
    apt-get update >> /usr/local/src/config-debian-apt-get.log
    DEBIAN_FRONTEND=noninteractive apt-get -y \
        -o DPkg::Options::=--force-confdef \
        -o DPkg::Options::=--force-confold \
        install git-core \
	build-essential \
	curl wget \
	openssl ssl-cert libssl-dev \
	apache2 libapache2-mod-proxy-html \
	php5 php5-curl php5-cli php5-intl php-apc >> /usr/local/src/config-debian-apt-get.log 

## change keymap ##
if [ "$CHANGE_KEYMAP" = true ] ; then
	echo "------------- configure keymap ----------------"
	DEBIAN_FRONTEND=noninteractive \
		apt-get -y install console-data \
        	console-setup \
		console-locales \
		keyboard-configuration > /usr/local/src/config-debian-keymap.log
	
	test "$?" -eq 0 && echo "keymap installed correctly"
fi

## Node, npm and bower ##
# node
   cd /usr/local/src
   git clone http://github.com/ry/node.git
# node compile
   
   cd /usr/local/src/node
   echo "------------- configure node ----------------"
   ./configure > /usr/local/src/config.log
   res=$? #assign the return of configure
   echo "------------- install node -------------------"
   test "$res" -eq 0 && make && make install >> /usr/local/src/config.log

   command -v node >/dev/null 2>&1 || { echo -e >&2 "\e[31mnode is not installed correclty.  Aborting.\e[0m"; exit 1; }

# npm install
   echo "------------- install npm --------------------"
   mkdir /usr/local/src/npm
   cd /usr/local/src/npm
   curl -O -L https://npmjs.org/install.sh
   sh install.sh
   
   command -v npm >/dev/null 2>&1 || { echo -e >&2 "\e[31mnpm is not installed correclty.  Aborting.\e[0m"; exit 1; }

# config and install with npm
   echo "-------------- install bower -----------------"
   npm install -g bower
   
   command -v bower >/dev/null 2>&1 || { echo -e >&2 "\e[31mbower is not installed correclty.  Aborting.\e[0m"; exit 1; }

# apache config
echo "-------------- apache config -----------------"
mkdir -p /var/www/web # create the web repot if it's not defined
chmod -R 700 /var/www/web # set all the right for the root
chown -R www-data:www-data /var/www/web  # change the owner to www-data
a2enmod php5 # enable the apache module php5
service apache2 reload # reload apache to be aware of the changes

echo "Job done ;)"


