#!/bin/bash

CHANGE_KEYMAP=false

## FLAG the option ##
while getopts ":a" opt; do
  case $opt in
    k)
      echo "change keymap activated" >&2
      CHANGE_KEYMAP=true
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      ;;
  esac
done

## APT-GET ##
    apt-get update
    DEBIAN_FRONTEND=noninteractive apt-get -y \
        -o DPkg::Options::=--force-confdef \
        -o DPkg::Options::=--force-confold \
        install git-core \
	build-essential \
	curl wget \
	openssl ssl-cert libssl-dev \
	apache2 libapache2-mod-proxy-html \
	php5 php5-curl php5-cli php5-intl php-apc 

## change keymap ##
if [ "$CHANGE_KEYMAP" = true ] ; then
	echo "------------- configure keymap ----------------"
	DEBIAN_FRONTEND=noninteractive \
		apt-get -y install console-data \
        	console-setup \
		console-locales \
		keyboard-configuration
	
	echo " keymap installed"
fi

## Node, npm and bower ##
   mkdir -p /usr/local/src
# node
   cd /usr/local/src
   git clone http://github.com/ry/node.git
# node compile
   
   cd /usr/local/src/node
   echo "------------- configure node ----------------"
   ./configure > /usr/local/src/config.log
   res=$? #assign the return of configure
   echo "result of configure node : $res"
   echo "------------- install node -------------------"
   $res && make && make install >> /usr/local/src/config.log

   command -v node >/dev/null 2>&1 || { echo -e >&2 "\e[31mnode is not installed correclty.  Aborting.\e[0m"; exit 1; }

# npm install
   echo "------------- install npm --------------------"
   mkdir /usr/local/src/npm
   cd /usr/local/src/npm
   curl -O -L https://npmjs.org/install.sh
   sh install.sh

# config and install with npm
   echo "-------------- install bower -----------------"
   npm install -g bower

# apache config
mkdir -p /var/www/web
chmod -R 700 /var/www/web
chown -R www-data:www-data /var/www/web 
a2enmod php5
service apache2 reload

echo "Job done ;)"


